#!/usr/bin/env python

import sys,os

def printXML(cliPath):
    xmlFP = open(cliPath + ".xml", "r")
    print(xmlFP.read())
    xmlFP.close()

def main ():
    remainingArgs = ['../dramms-install/bin/dramms',]
    for arg in sys.argv[1:]:
        if arg in ("-x", "--xml"):
            printXML(sys.argv[0])
            return
        else:
            remainingArgs.append(arg)

    command = "%s -a 0 -S %s -T %s -O %s -D %s" % tuple(remainingArgs)

    exit(os.system(command))

if __name__ == '__main__':
    try:
        main()
    except Exception, e:
        print ('ERROR, UNEXPECTED EXCEPTION')
        print str(e)
        import traceback
        traceback.print_exc()
