#!/usr/bin/env python

import sys,os

def printXML(cliPath):
    xmlFP = open(cliPath + ".xml", "r")
    print(xmlFP.read())
    xmlFP.close()

def main ():
    remainingArgs = []
    for arg in sys.argv[1:]:
        if arg in ("-x", "--xml"):
            printXML(sys.argv[0])
            return
        elif arg in ("-S", "--source"):
            print('input source image')
		elif arg in ("-T", "--target"):
			print('input target image')
		elif arg in ("-O", "--outimg"):
			print('output registered image')
		elif arg in ("-D", "--outdef"):
			print('output transformation')
        else:
            remainingArgs.append(arg)

    exit(os.system("echo Running command with: %s" % remainingArgs))

if __name__ == '__main__':
    try:
        main()
    except Exception, e:
        print ('ERROR, UNEXPECTED EXCEPTION')
        print str(e)
        import traceback
        traceback.print_exc()
